feat: update xdg-utils to 1.2.1-2

diff --git a/scripts/xdg-utils-common.in b/scripts/xdg-utils-common.in
--- a/scripts/xdg-utils-common.in
+++ b/scripts/xdg-utils-common.in
@@ -1,12 +1,13 @@
-
 #----------------------------------------------------------------------------
 #   Common utility functions included in all XDG wrapper scripts
 #----------------------------------------------------------------------------
 
+#shellcheck shell=sh
+
 DEBUG()
 {
   [ -z "${XDG_UTILS_DEBUG_LEVEL}" ] && return 0;
-  [ ${XDG_UTILS_DEBUG_LEVEL} -lt $1 ] && return 0;
+  [ "${XDG_UTILS_DEBUG_LEVEL}" -lt "$1" ] && return 0;
   shift
   echo "$@" >&2
 }
@@ -14,6 +15,7 @@ DEBUG()
 # This handles backslashes but not quote marks.
 first_word()
 {
+    # shellcheck disable=SC2162 # No -r is intended here
     read first rest
     echo "$first"
 }
@@ -23,9 +25,9 @@ first_word()
 binary_to_desktop_file()
 {
     search="${XDG_DATA_HOME:-$HOME/.local/share}:${XDG_DATA_DIRS:-/usr/local/share:/usr/share}"
-    binary="`which "$1"`"
-    binary="`readlink -f "$binary"`"
-    base="`basename "$binary"`"
+    binary="$(command -v "$1")"
+    binary="$(xdg_realpath "$binary")"
+    base="$(basename "$binary")"
     IFS=:
     for dir in $search; do
         unset IFS
@@ -37,11 +39,11 @@ binary_to_desktop_file()
             grep -q "^Exec.*$base" "$file" || continue
             # Make sure it's a visible desktop file (e.g. not "preferred-web-browser.desktop").
             grep -Eq "^(NoDisplay|Hidden)=true" "$file" && continue
-            command="`grep -E "^Exec(\[[^]=]*])?=" "$file" | cut -d= -f 2- | first_word`"
-            command="`which "$command"`"
-            if [ x"`readlink -f "$command"`" = x"$binary" ]; then
+            command="$(grep -E "^Exec(\[[^]=]*])?=" "$file" | cut -d= -f 2- | first_word)"
+            command="$(command -v "$command")"
+            if [ x"$(xdg_realpath "$command")" = x"$binary" ]; then
                 # Fix any double slashes that got added path composition
-                echo "$file" | sed -e 's,//*,/,g'
+                echo "$file" | tr -s /
                 return
             fi
         done
@@ -53,7 +55,7 @@ binary_to_desktop_file()
 desktop_file_to_binary()
 {
     search="${XDG_DATA_HOME:-$HOME/.local/share}:${XDG_DATA_DIRS:-/usr/local/share:/usr/share}"
-    desktop="`basename "$1"`"
+    desktop="$(basename "$1")"
     IFS=:
     for dir in $search; do
         unset IFS
@@ -62,10 +64,10 @@ desktop_file_to_binary()
         if [ "${desktop#*-}" != "$desktop" ]; then
             vendor=${desktop%-*}
             app=${desktop#*-}
-            if [ -r $dir/applications/$vendor/$app ]; then
-                file_path=$dir/applications/$vendor/$app
-            elif [ -r $dir/applnk/$vendor/$app ]; then
-                file_path=$dir/applnk/$vendor/$app
+            if [ -r "$dir/applications/$vendor/$app" ]; then
+                file_path="$dir/applications/$vendor/$app"
+            elif [ -r "$dir/applnk/$vendor/$app" ]; then
+                file_path="$dir/applnk/$vendor/$app"
             fi
         fi
         if test -z "$file_path" ; then
@@ -79,9 +81,9 @@ desktop_file_to_binary()
         fi
         if [ -r "$file_path" ]; then
             # Remove any arguments (%F, %f, %U, %u, etc.).
-            command="`grep -E "^Exec(\[[^]=]*])?=" "$file_path" | cut -d= -f 2- | first_word`"
-            command="`which "$command"`"
-            readlink -f "$command"
+            command="$(grep -E "^Exec(\[[^]=]*])?=" "$file_path" | cut -d= -f 2- | first_word)"
+            command="$(command -v "$command")"
+            xdg_realpath "$command"
             return
         fi
     done
@@ -90,10 +92,11 @@ desktop_file_to_binary()
 #-------------------------------------------------------------
 # Exit script on successfully completing the desired operation
 
+# shellcheck disable=SC2120 # It is okay to call this without arguments
 exit_success()
 {
     if [ $# -gt 0 ]; then
-        echo "$@"
+        echo "$*"
         echo
     fi
 
@@ -109,7 +112,7 @@ exit_success()
 exit_failure_syntax()
 {
     if [ $# -gt 0 ]; then
-        echo "@NAME@: $@" >&2
+        echo "@NAME@: $*" >&2
         echo "Try '@NAME@ --help' for more information." >&2
     else
         usage
@@ -125,7 +128,7 @@ exit_failure_syntax()
 exit_failure_file_missing()
 {
     if [ $# -gt 0 ]; then
-        echo "@NAME@: $@" >&2
+        echo "@NAME@: $*" >&2
     fi
 
     exit 2
@@ -137,7 +140,7 @@ exit_failure_file_missing()
 exit_failure_operation_impossible()
 {
     if [ $# -gt 0 ]; then
-        echo "@NAME@: $@" >&2
+        echo "@NAME@: $*" >&2
     fi
 
     exit 3
@@ -149,7 +152,7 @@ exit_failure_operation_impossible()
 exit_failure_operation_failed()
 {
     if [ $# -gt 0 ]; then
-        echo "@NAME@: $@" >&2
+        echo "@NAME@: $*" >&2
     fi
 
     exit 4
@@ -161,7 +164,7 @@ exit_failure_operation_failed()
 exit_failure_file_permission_read()
 {
     if [ $# -gt 0 ]; then
-        echo "@NAME@: $@" >&2
+        echo "@NAME@: $*" >&2
     fi
 
     exit 5
@@ -173,7 +176,7 @@ exit_failure_file_permission_read()
 exit_failure_file_permission_write()
 {
     if [ $# -gt 0 ]; then
-        echo "@NAME@: $@" >&2
+        echo "@NAME@: $*" >&2
     fi
 
     exit 6
@@ -193,7 +196,7 @@ check_vendor_prefix()
 {
     file_label="$2"
     [ -n "$file_label" ] || file_label="filename"
-    file=`basename "$1"`
+    file="$(basename "$1")"
     case "$file" in
        [[:alpha:]]*-*)
          return
@@ -216,7 +219,7 @@ check_output_file()
             exit_failure_file_permission_write "no permission to write to file '$1'"
         fi
     else
-        DIR=`dirname "$1"`
+        DIR="$(dirname "$1")"
         if [ ! -w "$DIR" ] || [ ! -x "$DIR" ]; then
             exit_failure_file_permission_write "no permission to create file '$1'"
         fi
@@ -245,9 +248,13 @@ check_common_commands()
             ;;
 
             --version)
-            echo "@NAME@ 1.1.3"
+            echo "@NAME@ 1.2.1"
             exit_success
             ;;
+
+            --)
+	        [ -z "$XDG_UTILS_ENABLE_DOUBLE_HYPEN" ] || break
+	        ;;
         esac
     done
 }
@@ -255,7 +262,8 @@ check_common_commands()
 check_common_commands "$@"
 
 [ -z "${XDG_UTILS_DEBUG_LEVEL}" ] && unset XDG_UTILS_DEBUG_LEVEL;
-if [ ${XDG_UTILS_DEBUG_LEVEL-0} -lt 1 ]; then
+# shellcheck disable=SC2034
+if [ "${XDG_UTILS_DEBUG_LEVEL-0}" -lt 1 ]; then
     # Be silent
     xdg_redirect_output=" > /dev/null 2> /dev/null"
 else
@@ -288,9 +296,8 @@ detectDE()
          KDE)
            DE=kde;
            ;;
-         # Deepin Desktop Environments
          DEEPIN|Deepin|deepin)
-           DE=dde;
+           DE=deepin;
            ;;
          LXDE)
            DE=lxde;
@@ -310,27 +317,28 @@ detectDE()
       esac
     fi
 
-    if [ x"$DE" = x"" ]; then
+    # shellcheck disable=SC2153
+    if [ -z "$DE" ]; then
       # classic fallbacks
-      if [ x"$KDE_FULL_SESSION" != x"" ]; then DE=kde;
-      elif [ x"$GNOME_DESKTOP_SESSION_ID" != x"" ]; then DE=gnome;
-      elif [ x"$MATE_DESKTOP_SESSION_ID" != x"" ]; then DE=mate;
-      elif `dbus-send --print-reply --dest=org.freedesktop.DBus /org/freedesktop/DBus org.freedesktop.DBus.GetNameOwner string:org.gnome.SessionManager > /dev/null 2>&1` ; then DE=gnome;
+      if [ -n "$KDE_FULL_SESSION" ]; then DE=kde;
+      elif [ -n "$GNOME_DESKTOP_SESSION_ID" ]; then DE=gnome;
+      elif [ -n "$MATE_DESKTOP_SESSION_ID" ]; then DE=mate;
+      elif dbus-send --print-reply --dest=org.freedesktop.DBus /org/freedesktop/DBus org.freedesktop.DBus.GetNameOwner string:org.gnome.SessionManager > /dev/null 2>&1 ; then DE=gnome;
       elif xprop -root _DT_SAVE_MODE 2> /dev/null | grep ' = \"xfce4\"$' >/dev/null 2>&1; then DE=xfce;
       elif xprop -root 2> /dev/null | grep -i '^xfce_desktop_window' >/dev/null 2>&1; then DE=xfce
-      elif echo $DESKTOP | grep -q '^Enlightenment'; then DE=enlightenment;
-      elif [ x"$LXQT_SESSION_CONFIG" != x"" ]; then DE=lxqt;
+      elif echo "$DESKTOP" | grep -q '^Enlightenment'; then DE=enlightenment;
+      elif [ -n "$LXQT_SESSION_CONFIG" ]; then DE=lxqt;
       fi
     fi
 
-    if [ x"$DE" = x"" ]; then
+    if [ -z "$DE" ]; then
       # fallback to checking $DESKTOP_SESSION
       case "$DESKTOP_SESSION" in
          gnome)
            DE=gnome;
            ;;
          LXDE|Lubuntu)
-           DE=lxde; 
+           DE=lxde;
            ;;
          MATE)
            DE=mate;
@@ -341,14 +349,19 @@ detectDE()
       esac
     fi
 
-    if [ x"$DE" = x"" ]; then
+    if [ -z "$DE" ]; then
       # fallback to uname output for other platforms
-      case "$(uname 2>/dev/null)" in 
+      case "$(uname 2>/dev/null)" in
         CYGWIN*)
           DE=cygwin;
           ;;
         Darwin)
           DE=darwin;
+          ;;
+        Linux)
+          grep -q microsoft /proc/version > /dev/null 2>&1 && \
+          command -v explorer.exe > /dev/null 2>&1 && \
+          DE=wsl;
           ;;
       esac
     fi
@@ -356,7 +369,7 @@ detectDE()
     if [ x"$DE" = x"gnome" ]; then
       # gnome-default-applications-properties is only available in GNOME 2.x
       # but not in GNOME 3.x
-      which gnome-default-applications-properties > /dev/null 2>&1  || DE="gnome3"
+      command -v gnome-default-applications-properties > /dev/null || DE="gnome3"
     fi
 
     if [ -f "$XDG_RUNTIME_DIR/flatpak-info" ]; then
@@ -371,13 +384,13 @@ detectDE()
 
 kfmclient_fix_exit_code()
 {
-    version=`LC_ALL=C.UTF-8 kde-config --version 2>/dev/null | grep '^KDE'`
-    major=`echo $version | sed 's/KDE.*: \([0-9]\).*/\1/'`
-    minor=`echo $version | sed 's/KDE.*: [0-9]*\.\([0-9]\).*/\1/'`
-    release=`echo $version | sed 's/KDE.*: [0-9]*\.[0-9]*\.\([0-9]\).*/\1/'`
-    test "$major" -gt 3 && return $1
-    test "$minor" -gt 5 && return $1
-    test "$release" -gt 4 && return $1
+    version="$(LC_ALL=C.UTF-8 kde-config --version 2>/dev/null | grep '^KDE')"
+    major="$(echo "$version" | sed 's/KDE.*: \([0-9]\).*/\1/')"
+    minor="$(echo "$version" | sed 's/KDE.*: [0-9]*\.\([0-9]\).*/\1/')"
+    release="$(echo "$version" | sed 's/KDE.*: [0-9]*\.[0-9]*\.\([0-9]\).*/\1/')"
+    test "$major" -gt 3 && return "$1"
+    test "$minor" -gt 5 && return "$1"
+    test "$release" -gt 4 && return "$1"
     return 0
 }
 
@@ -391,4 +404,60 @@ has_display()
     else
         return 1
     fi
+}
+
+#----------------------------------------------------------------------------
+# Prefixes a path with a "./" if it starts with a "-".
+# This is useful for programs to not confuse paths with options.
+
+unoption_path()
+{
+	case "$1" in
+		-*)
+			printf "./%s" "$1" ;;
+		*)
+			printf "%s" "$1" ;;
+	esac
+}
+
+#----------------------------------------------------------------------------
+# Performs a symlink and relative path resolving for a single argument.
+# This will always fail if the given file does not exist!
+
+xdg_realpath()
+{
+	# allow caching and external configuration
+	if [ -z "$XDG_UTILS_REALPATH_BACKEND" ] ; then
+		if command -v realpath >/dev/null 2>/dev/null ; then
+			lines="$(realpath -- / 2>&1)"
+			if [ $? = 0 ] && [ "$lines" = "/" ] ; then
+				XDG_UTILS_REALPATH_BACKEND="realpath"
+			else
+				# The realpath took the -- literally, probably the busybox implementation
+				XDG_UTILS_REALPATH_BACKEND="busybox-realpath"
+			fi
+			unset lines
+		elif command -v readlink >/dev/null 2>/dev/null ; then
+			XDG_UTILS_REALPATH_BACKEND="readlink"
+		else
+			exit_failure_operation_failed "No usable realpath backend found. Have a realpath binary or a readlink -f that canonicalizes paths."
+		fi
+	fi
+	# Always fail if the file doesn't exist (busybox realpath does that for example)
+	[ -e "$1" ] || return 1
+	case "$XDG_UTILS_REALPATH_BACKEND" in
+		realpath)
+			realpath -- "$1"
+			;;
+		busybox-realpath)
+			# busybox style realpath implementations have options too
+			realpath "$(unoption_path "$1")"
+			;;
+		readlink)
+			readlink -f "$(unoption_path "$1")"
+			;;
+		*)
+			exit_failure_operation_impossible "Realpath backend '$XDG_UTILS_REALPATH_BACKEND' not recognized."
+			;;
+	esac
 }
